# Generated by Django 4.1.6 on 2023-02-13 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('bank', models.CharField(max_length=250)),
                ('salary_min', models.IntegerField()),
                ('salary_max0', models.IntegerField()),
                ('craeted_date', models.DateTimeField(default=datetime.datetime(2023, 2, 13, 13, 12, 32, 568421, tzinfo=datetime.timezone.utc))),
                ('position_description', models.TextField()),
                ('demands', models.TextField()),
                ('conditions', models.TextField()),
                ('appeal', models.TextField()),
                ('company_description', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='')),
                ('job_image', models.ImageField(upload_to='images/')),
                ('bank_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
