# Generated by Django 4.1.6 on 2023-02-14 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0003_job_education_alter_job_craeted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='craeted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 9, 56, 35, 112615, tzinfo=datetime.timezone.utc)),
        ),
    ]
