# Generated by Django 4.1.6 on 2023-02-16 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0005_alter_job_craeted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='craeted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 7, 47, 43, 533294, tzinfo=datetime.timezone.utc)),
        ),
    ]
