# Generated by Django 4.1.6 on 2023-02-16 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0006_alter_job_craeted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='name_az',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='craeted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 7, 52, 10, 738054, tzinfo=datetime.timezone.utc)),
        ),
    ]
