# Generated by Django 4.1.6 on 2023-02-16 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0007_education_name_az_education_name_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Education',
            new_name='education',
        ),
        migrations.AddField(
            model_name='job',
            name='address_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='address_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='address_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='appeal_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='appeal_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='appeal_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='bank_az',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='bank_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='bank_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='category_az',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showlist.category'),
        ),
        migrations.AddField(
            model_name='job',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showlist.category'),
        ),
        migrations.AddField(
            model_name='job',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showlist.category'),
        ),
        migrations.AddField(
            model_name='job',
            name='city_az',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showlist.city'),
        ),
        migrations.AddField(
            model_name='job',
            name='city_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showlist.city'),
        ),
        migrations.AddField(
            model_name='job',
            name='city_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showlist.city'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='conditions_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='conditions_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='conditions_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='demands_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='demands_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='demands_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='education_az',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showlist.education'),
        ),
        migrations.AddField(
            model_name='job',
            name='education_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showlist.education'),
        ),
        migrations.AddField(
            model_name='job',
            name='education_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showlist.education'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_az',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showlist.experience'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showlist.experience'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showlist.experience'),
        ),
        migrations.AddField(
            model_name='job',
            name='position_description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='position_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='position_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='premium_az',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='premium_en',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='premium_ru',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='title_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='craeted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 8, 6, 59, 387197, tzinfo=datetime.timezone.utc)),
        ),
    ]
