# Generated by Django 4.1.6 on 2023-02-16 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0009_category_name_az_category_name_en_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='craeted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 9, 44, 56, 816722, tzinfo=datetime.timezone.utc)),
        ),
    ]
