# Generated by Django 4.1.6 on 2023-02-16 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0010_alter_job_craeted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='craeted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 9, 45, 4, 271411, tzinfo=datetime.timezone.utc)),
        ),
    ]
