# Generated by Django 4.1.6 on 2023-02-16 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0012_alter_job_craeted_date_alter_job_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category_az',
        ),
        migrations.RemoveField(
            model_name='job',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='job',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='job',
            name='city_az',
        ),
        migrations.RemoveField(
            model_name='job',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='job',
            name='city_ru',
        ),
        migrations.RemoveField(
            model_name='job',
            name='education_az',
        ),
        migrations.RemoveField(
            model_name='job',
            name='education_en',
        ),
        migrations.RemoveField(
            model_name='job',
            name='education_ru',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience_az',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience_en',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience_ru',
        ),
        migrations.RemoveField(
            model_name='job',
            name='premium_az',
        ),
        migrations.RemoveField(
            model_name='job',
            name='premium_en',
        ),
        migrations.RemoveField(
            model_name='job',
            name='premium_ru',
        ),
        migrations.AlterField(
            model_name='job',
            name='craeted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 13, 38, 36, 188733, tzinfo=datetime.timezone.utc)),
        ),
    ]
