# Generated by Django 4.1.6 on 2023-02-20 07:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0013_remove_job_category_az_remove_job_category_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='craeted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 7, 3, 51, 338800, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='showlist.price'),
        ),
    ]
