# Generated by Django 4.1.6 on 2023-02-20 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0016_alter_job_craeted_date_alter_job_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='craeted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 7, 30, 35, 549570, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
