# Generated by Django 4.1.6 on 2023-02-20 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0017_alter_job_craeted_date_alter_job_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='craeted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 9, 55, 20, 515954, tzinfo=datetime.timezone.utc)),
        ),
    ]
