# Generated by Django 4.1.6 on 2023-02-20 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0018_advertising_alter_job_craeted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='craeted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 9, 57, 28, 212037, tzinfo=datetime.timezone.utc)),
        ),
    ]
