# Generated by Django 4.1.6 on 2023-02-20 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0019_advertising_show_alter_job_craeted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertising',
            old_name='job_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='job',
            name='craeted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 10, 0, 15, 744811, tzinfo=datetime.timezone.utc)),
        ),
    ]
