# Generated by Django 4.1.6 on 2023-02-21 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0020_rename_job_image_advertising_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_image',
        ),
        migrations.AlterField(
            model_name='job',
            name='craeted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 10, 51, 23, 284067, tzinfo=datetime.timezone.utc)),
        ),
    ]
